# Generated by Django 4.0.3 on 2022-03-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfancia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrozonal',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='regionales',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default=1, max_length=1),
        ),
    ]
